# Copyright 2020 Vauxoo
# License LGPL-3 or later (http://www.gnu.org/licenses/lgpl).
{
    'name': 'Instance Creator for Stellar',
    'summary': '''
    Instance creator for stellar. This is the app.
    ''',
    'author': 'Vauxoo',
    'website': 'https://www.vauxoo.com',
    'license': 'LGPL-3',
    'category': 'Installer',
    'version': '12.0.1.0.3',
    'depends': [
        'account_batch_payment',
        'account_cancel',
        'account_check_printing',
        'account_payment',
        'account_reports_followup',
        'base_import_module',
        'base_vat',
        'board',
        'company_country',
        'crm',
        'delivery',
        'l10n_ca',
        'sale_coupon',
        'sale_margin',
        'stock_barcode',
        'stock_dropshipping',
        'theme_bootswatch',
        'website_form_editor',
        'website_partner',
        'website_sale',
        'website_sale_delivery'
    ],
    'test': [
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/res_company.xml',
        'data/delivery.xml',
        'data/ir_attachment.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'data/crm_team.xml',
        'data/res_company.xml',
        'data/website.xml',
        'report/report_dwjo_views.xml',
        'report/report_dwjo.xml',
        'report/report_dwjo_template.xml',
        # Views
        'views/assets.xml',
        'views/bank_statement_view.xml',
        'views/delivery_views.xml',
        'views/payment_views.xml',
        'views/res_users_views.xml',
        'views/sale_order_views.xml',
        'views/templates/website_sale_templates.xml',
        'views/templates/payment_templates.xml',
        'views/templates/portal_templates.xml',
        'data/payment_acquirer.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
